---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tilbakemeldinger-api
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: tilbakemeldinger
          namespace: personbruker
          cluster: {{ gcp-cluster }}
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/ssl/ca-bundle.pem"
  envFrom:
    - secret: tilbakemeldinger
  resources:
    limits:
      cpu: '3'
      memory: 1500Mi
    requests:
      memory: 1500Mi
