---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tilbakemeldinger-api
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: tilbakemeldinger
          namespace: personbruker
          cluster: {{ gcp-cluster }}
        - application: samisk-samtale-bestilling
          namespace: personbruker
          cluster: {{ gcp-cluster }}
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/ssl/ca-bundle.pem"
  envFrom:
    - secret: tilbakemeldinger
  vault:
    enabled: true
  replicas:
  {{#with replicas}}
    min: {{min}}
    max: {{max}}
  {{/with}}
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: {{ cpuReq }}
      memory: 128Mi
